name: konsi_challenge
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  brasil_fields: 1.6.0
  cupertino_icons: 1.0.2
  dio: 4.0.6
  floor: 1.3.0
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.1
  flutter_dotenv: 5.0.2
  flutter_hooks: 0.18.5+1
  get_it: 7.2.0
  http: 0.13.5
  maps_launcher: 2.0.1

dev_dependencies:
  bloc_test: 9.1.0
  build_runner: 2.2.1
  floor_generator: 1.3.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mocktail: 0.3.0

flutter:
  assets:
    - assets/env/
  uses-material-design: true

























